name: dex
director_uuid: <CHANGE ME>

releases:
 - name: dex
   version: latest
 - name: postgres
   version: latest

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

instance_groups:
  - name: dex
    jobs:
      - name: postgres
        release: postgres
      - name: dex_worker
        release: dex
      - name: dex_overlord
        release: dex
    instances: 1
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    azs:
      - default
    networks:
      - name: default
        static_ips:
          - 10.244.0.2

properties:
  databases:
    db_scheme: postgres
    port: 5524
    address: 127.0.0.1
    databases:
      - name: dexdb
        tag: dex
    roles:
      - name: dexadmin
        password: chAng3m3
        tag: dex

  dex:
    worker:
      db_url: "postgres://dexadmin:chAng3m3@127.0.0.1:5524/dexdb?sslmode=disable"
      key_secrets: "f1nmgYJ79CDgU3bYim+kfcvEoqIkLwNdK3FA6g6DoUQ="
      log_debug: true
      tls_cert: |
        -----BEGIN CERTIFICATE-----
        MIIESTCCAjGgAwIBAgIRAOtqTKiqMP+td1ashaSYbHgwDQYJKoZIhvcNAQELBQAw
        DTELMAkGA1UEAxMCY2EwHhcNMTYwOTA2MTcwMDUxWhcNMTgwOTA2MTcwMDUxWjAV
        MRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
        CgKCAQEAxuoarpXtDpeSxAhuJk0eHFLLXMdypmjEVh/SO+Qe2bWvXiFw+g3XOV6x
        MlRzjdLawcZyCCXOt4lTbzmyjP5hux0oPmCWSTHYs1VGzBK2wKV+0EijUR93CH5j
        fSm+cDJ7ZFbztZ9LsVUCVz0ZewEF75l7TKV60DANsEk97QQOphp09r7karvA/Aip
        HjNG84kzemxZrIiIwIVr/vWLxhZH4YAfFMjTm4lmnFWnGwjIiY+uA1fd4x4lO8G1
        FZVTw4jmgJnoJ9WY5gLvHaQwAr5E0FkRhoTBR+VT3POoNLV3Ou0gmTEbyvSvwddM
        ePcic13VHNgvWt9xw8AAOMqgjKOUrQIDAQABo4GbMIGYMA4GA1UdDwEB/wQEAwID
        uDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFBO8jtVD
        rI7EMYBlQ0xzxCNlFyeDMB8GA1UdIwQYMBaAFNzN7gxkvH3wPeP1OH4sd/UDm7d/
        MCcGA1UdEQQgMB6HBAogAAGHBAr0AAOHBAr0AASHBAr0AAWHBAr0AAYwDQYJKoZI
        hvcNAQELBQADggIBAKXFlOHNF/IHz6CzwFIy6I2/D3hSctcf2iHRWSoRLRsdZcsL
        BOXmckx3jKolzmqtrYCrtCE8EMEFvpzEedHMDaGhanCFM2br3LIFq9GSfV+YSnC0
        oA+SEcaGkKSgz66KFQIq56IAKfwjOPGjbtWkfb63lkBtS4y59NI6dwLjKgoLt/6M
        eGkQAwQXDeUceyfo8tW/m9AXb8NVTXd4q2y+9zHSq9xtmKkl0fRjqt/9BrsE2RTj
        6KYy9WDmMMrsspKpDCpg4y4BonWbD8RocZM9167rjD9xr1SkkWYEecAca7ui660+
        MDZa8+kbfxJkR6QeepMdFUYgL94Ey0Pzr7tKvQJW2TaK1JOJ2XmAZmBIdIX9T76r
        F9ny1FSnonC6+0t806efIgvKGJ8iVMIcZVqEvxWRDAEDUD504SYY3j30R6KXtIb8
        GQMU4ire1Q2Ltdd4iJvZg55XPeKEFM75wNqN+/bi+EJ5l5DtHTHSlMfg4jlysK99
        SPrzOi97+0/9oNiJkMQG5TkPHophaxs1C4WdrkZ1JvL8owf1nPaZ0r/XVxGCQ6oE
        uqrskgg8rM0GdBR2b9CUHuh56CGyIlCnTXiPZzIRfJLGFP6VdsdsaY3EikZeUfQH
        8qF/ieDe6gj4CEnTjZEDAZC2HDxTfwraRnnQaj0/pHDNibqWH0ul8SIzLCdj
        -----END CERTIFICATE-----
      tls_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpgIBAAKCAQEAxuoarpXtDpeSxAhuJk0eHFLLXMdypmjEVh/SO+Qe2bWvXiFw
        +g3XOV6xMlRzjdLawcZyCCXOt4lTbzmyjP5hux0oPmCWSTHYs1VGzBK2wKV+0Eij
        UR93CH5jfSm+cDJ7ZFbztZ9LsVUCVz0ZewEF75l7TKV60DANsEk97QQOphp09r7k
        arvA/AipHjNG84kzemxZrIiIwIVr/vWLxhZH4YAfFMjTm4lmnFWnGwjIiY+uA1fd
        4x4lO8G1FZVTw4jmgJnoJ9WY5gLvHaQwAr5E0FkRhoTBR+VT3POoNLV3Ou0gmTEb
        yvSvwddMePcic13VHNgvWt9xw8AAOMqgjKOUrQIDAQABAoIBAQDAdKcmPjcjxDGj
        bAivFDRK8SyD8xGRwpIcRiOSAPB8clZfu/lkZtnTTzQg3ycClH1FuSyBh5sPZ1YL
        qoZ/9mw2r0pNuAQQg6MIOD0MnBqoIDenbHBfwBLaa/b0ldwFEELk3WBlXN/OjtJ5
        98rcgSvuG9D5Yq6GGchUxTieRyupNv8fc2VlSZj011muOTx3MNnI9mT5yD6NQow7
        s7XjSATWpJiorX6uyLKLSKnYVcAzLyUybY4WM+7qFGOafg48iaNdEj6kJHS0iS+A
        nkChBfL5WPIqHrkQmpS2cjwInzh9Utj41qCBSuR3AzCcYAK4iHUtZIZCNkMw/sNy
        c7vcKZOBAoGBAMxqsOcLs8TSEJ7n2zIB0u9kptoYW97bkC2wxLQmGm58GD7A5jJy
        V22ueiECocKkhsKt8DIriP3CymnY1ZMNzFQLzfVXb5eLf1yTPfF70BUnfsuK6ix4
        K0BIiz27J0oexMo0vDRU8PoJZhBi6jqhf8u+iEq0s49h8MexORACec+hAoGBAPkb
        9yrnq0KA9Hb8h9DblRVpKSq/KZ05LN8AFv07dLJZUP7rzKtXgV08R+d0UiPZ/+Lm
        xbeYhQuCoEBab8FQJ7KeT0ERLzAMfnHmZd4m6deRpYteBm/AfNBA/3LdaI92zBaj
        DWMI0QfkQ632pVtheQRTkfDCCu82JXzX8jUyVZmNAoGBAK88Atx9vqTKA2+FiPVs
        dNu9p/8shI0eIZHZiDZ6t4vhG5OoH249cM9Yk996dxr5mYCIRXFsuqn28zgbprLC
        UFf4Kp3YT5RVBGBi5OX/YpjP27U3J5nphgI8bgkESCEVEVPaM0CVVGKz7ee8M9kB
        GyGY+xM3pvoSVquJNEaSKMQhAoGBAM4U1ZiYCXU+C3/4ED+3uJD664SimsGn0Dg3
        8czTCAqXm0sZNbu1655/RRj0gROJwIgs0/q74a0RBpPWfUeWkRDSqMwydDAy1dRS
        f4mV9bRRmHtAcOC4hEkgzHNxOZQd+l7ryyJX4928eEUNm+SKMbxjioN7c+JLkB3E
        5Gof1vLtAoGBALL8aVHW+4MMzDf5ypGx5snopIa878D94EJAZ+iNi+zJm1BEA6TK
        sHIVnElvxpvWb8P1v78fEOxdI63a06IlqZkevQ3iT9MnVkyxWEc4+IiuqdOvcO/p
        fpeIzCnFxUwf+dmM9kWeCqQnIJnYGeO0S8H/AqWZYLDRp/88PG/TNchY
        -----END RSA PRIVATE KEY-----
    overlord:
      admin_api_secret: "ENy7fOx7F3ip0XKxV/s5IPNHGMI85bPDfEHVDhJ4XkiHVou9lftkuf06AI8pPod6PeDKEI5dFyXvW2J31QgxF6TUcdE095nDw2LqM3Tq4UUx2ZmypMAfiu+TxLhkDAadEb0qdMK4B0fLyAbHMqz/C4T0j4eaQfVGOcTasdrXttE="
      log_debug: true
