name: dex

instance_groups:
  - name: dex
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: dex
        release: dex
        properties:
          dex:
            connectors:
              - type: mockCallback
                id: mock
                name: Example

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

releases:
  - name: dex
    version: latest
