# Apply to your cf-deployment based Cloud Foundry

# UAA client for dex
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/dex?
  value:
    authorized-grant-types: authorization_code
    authorities: uaa.none
    scope: openid
    secret: "((uaa_clients_dex_secret))"

- type: replace
  path: /variables?/-
  value:
    name: uaa_clients_dex_secret
    type: password
